
resources:
  - url: /hacsfiles/secondaryinfo-entity-row/secondaryinfo-entity-row.js
    type: module
  - url: /hacsfiles/vertical-stack-in-card/vertical-stack-in-card.js
    type: module
  - url: /hacsfiles/custom-header/custom-header.js
    type: module
  - url: /hacsfiles/lovelace-card-tools/card-tools.
    type: module








custom_header:
  compact_mode: true
  hide_help: true
  hide_config: true
  shadow: on
  chevrons: false

title: US Home
views:
  - badges:
      - entity: binary_sensor.updater
      - entity: person.us_home
    cards:
      - entity: weather.home
        type: weather-forecast
      - entities:
          - entity: input_boolean.notify_home
        type: entities
      - type: glance
        entities:
          - entity: sensor.cpu_wen_du
          - entity: sensor.processor_use
          - entity: sensor.memory_use_percent
          - entity: sensor.disk_use_percent_home
        title: 系统
    path: default_view
    title: Home
  - title: Living Room